export const SET_LOADING = 'SET_LOADING'

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const SET_USER = 'SET_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
