export const SET_LOADING = 'SET_LOADING'

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const SET_USER = 'SET_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const AUTH_CHECK_DONE='AUTH_CHECK_DONE'

export const SUBMIT_SYMPTOMS_SUCCESS='SUBMIT_SYMPTOMS_SUCCESS'
export const SUBMIT_SYMPTOMS_ERROR='SUBMIT_SYMPTOMS_ERROR'

export const SEND_CHAT_SUCCESS='SEND_CHAT_SUCCESS'
export const SEND_CHAT_ERROR='SEND_CHAT_ERROR'

export const FETCH_PLACE_SUCCESS='FETCH_PLACE_SUCCESS'
export const FETCH_PLACE_ERROR='FETCH_PLACE_ERROR'

export const FETCH_ALL_CHAT_SUCCESS='FETCH_ALL_CHAT_SUCCESS'
export const FETCH_ALL_CHAT_ERROR='FETCH_ALL_CHAT_ERROR'

export const FETCH_ALL_SYMPTOM_SUCCESS='FETCH_ALL_SYMPTOM_SUCCESS'
export const FETCH_ALL_SYMPTOM_ERROR='FETCH_ALL_SYMPTOM_ERROR'

export const FETCH_PROFILE_INFO_SUCCESS='FETCH_PROFILE_INFO_SUCCESS'
export const FETCH_PROFILE_INFO_ERROR='FETCH_PROFILE_INFO_ERROR'
                       
export const CREATE_HEALTH_GOAL_SUCCESS='CREATE_HEALTH_GOAL_SUCCESS'
export const CREATE_HEALTH_GOAL_ERROR='CREATE_HEALTH_GOAL_ERROR'

export const FETCH_HEALTH_GOAL_SUCCESS='FETCH_HEALTH_GOAL_SUCCESS'
export const FETCH_HEALTH_GOAL_ERROR='FETCH_HEALTH_GOAL_ERROR'

export const SET_ERROR='SET_ERROR'